parameters:
  name: ""
  vmImage: ""
  matrix: []

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      REPO_DIR: "pandas"
      BUILD_COMMIT: "v1.0.1"
      PLAT: "x86_64"
      NP_BUILD_DEP: "numpy==1.13.3"
      CYTHON_BUILD_DEP: "cython==0.29.13"
      NIGHTLY_BUILD_COMMIT: "master"
      NIGHTLY_BUILD: "false"
      TEST_DEPENDS: "pytest pytest-xdist hypothesis"
      JUNITXML: "test-data.xml"
      TEST_DIR: "tmp_for_test"
    strategy:
      matrix:
        ${{ insert }}: ${{ parameters.matrix }}

    steps:
      - checkout: self
        submodules: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(MB_PYTHON_VERSION)
        displayName: Set python version

      - bash: |
          set -e

          SKIP_BUILD="false"
          if [ "$BUILD_REASON" == "Schedule" ]; then
            BUILD_COMMIT=$NIGHTLY_BUILD_COMMIT
            if [ "$NIGHTLY_BUILD" != "true" ]; then
              SKIP_BUILD="true"
            fi
          fi
          echo "Building pandas@$BUILD_COMMIT"
          echo "##vso[task.setvariable variable=BUILD_COMMIT]$BUILD_COMMIT"
          echo "##vso[task.setvariable variable=SKIP_BUILD]$SKIP_BUILD"

          # Platform variables used in multibuild scripts
          if [ `uname` == 'Darwin' ]; then
            echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]osx"
            echo "##vso[task.setvariable variable=MACOSX_DEPLOYMENT_TARGET]10.9"
          else
            echo "##vso[task.setvariable variable=TRAVIS_OS_NAME]linux"
          fi

          # Store original Python path to be able to create test_venv pointing
          # to same Python version.
          PYTHON_EXE=`which python`
          echo "##vso[task.setvariable variable=PYTHON_EXE]$PYTHON_EXE"
        displayName: Define build env variables

      - bash: |
          set -e
          pip install virtualenv
          BUILD_DEPENDS="$NP_BUILD_DEP $CYTHON_BUILD_DEP"

          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          source extra_functions.sh

          # Setup build dependencies
          before_install

          clean_code $REPO_DIR $BUILD_COMMIT
          build_wheel $REPO_DIR $PLAT
        displayName: Build wheel
        condition: eq(variables['SKIP_BUILD'], 'false')

      - bash: |
          set -xe
          source multibuild/common_utils.sh
          source multibuild/travis_steps.sh
          source extra_functions.sh
          setup_test_venv
          install_run $PLAT
          teardown_test_venv
        displayName: Install wheel and test
        condition: eq(variables['SKIP_BUILD'], 'false')

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '$(TEST_DIR)/$(JUNITXML)'
          testRunTitle: ${{ format('{0}-$(Agent.JobName)', parameters.name) }}
        displayName: 'Publish Test Results'
        condition: eq(variables['SKIP_BUILD'], 'false')

      - bash: |
          echo "##vso[task.prependpath]$CONDA/bin"
          sudo chown -R $USER $CONDA
        displayName: Add conda to PATH
        condition: and(succeeded(), eq(variables['SKIP_BUILD'], 'false'), ne(variables['Build.Reason'], 'PullRequest'))

      - bash: conda install -q -y anaconda-client
        displayName: Install anaconda-client
        condition: and(succeeded(), eq(variables['SKIP_BUILD'], 'false'), ne(variables['Build.Reason'], 'PullRequest'))

      - bash: |
          set -e
          if [ "$BUILD_REASON" == "Schedule" ]; then
            ANACONDA_ORG="scipy-wheels-nightly"
            TOKEN="$PANDAS_NIGHTLY_UPLOAD_TOKEN"
          else
            ANACONDA_ORG="multibuild-wheels-staging"
            TOKEN="$PANDAS_STAGING_UPLOAD_TOKEN"
          fi
          if [ "$TOKEN" == "" ]; then
            echo "##[warning] Could not find anaconda.org upload token in secret variables"
          fi
          echo "##vso[task.setvariable variable=TOKEN]$TOKEN"
          echo "##vso[task.setvariable variable=ANACONDA_ORG]$ANACONDA_ORG"
        displayName: Retrieve secret upload token
        condition: and(succeeded(), eq(variables['SKIP_BUILD'], 'false'), ne(variables['Build.Reason'], 'PullRequest'))
        env:
          # Secret variables need to mapped to env variables explicitly:
          PANDAS_NIGHTLY_UPLOAD_TOKEN: $(PANDAS_NIGHTLY_UPLOAD_TOKEN)
          PANDAS_STAGING_UPLOAD_TOKEN: $(PANDAS_STAGING_UPLOAD_TOKEN)

      - bash: |
          set -e
          # The --force option forces a replacement if the remote file already
          # exists.
          ls wheelhouse/*.whl
          anaconda -t $TOKEN upload --force -u $ANACONDA_ORG wheelhouse/*.whl
          echo "PyPI-style index: https://pypi.anaconda.org/$ANACONDA_ORG/simple"
        displayName: Upload to anaconda.org (only if secret token is retrieved)
        condition: ne(variables['TOKEN'], '')
